# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /kinect/depth_registered/points
    filtered_cloud_topic: filtered_cloud
    max_range: 5.0
    frame_subsample: 1
    point_subsample: 1
    max_update_rate: 1.0
    padding_offset: 0.1
    padding_scale: 1.0